"""Tool handlers for the voice pipeline.

Every tool goes through :func:`~spatalk.brain.driver.run_tool`, so the spoken
sentence is rendered from the tenant scripts and never re-generated by the model. The
result callback therefore sets ``run_llm=False``: the model does not get to paraphrase
what happened.
"""

from __future__ import annotations

from loguru import logger
from pipecat.frames.frames import EndFrame, FunctionCallResultProperties, TTSSpeakFrame
from pipecat.services.llm_service import FunctionCallParams

from spatalk.brain.driver import run_tool
from spatalk.brain.flow import tool_refusal
from spatalk.voice.steps import next_question, sync_context
from spatalk.brain.outcomes import Captured, Completed, Refused, Transferred
from spatalk.brain.renderer import render, render_script
from spatalk.brain.requests import TransferRequest
from spatalk.brain.tools import TOOL_NAMES, TRANSFER_TOOL
from spatalk.voice.session import VoiceSession
from spatalk.voice.transfer import attempt_transfer, mask_number, suppress_auto_hangup


def register_tool_handlers(llm, session: VoiceSession) -> None:
    for name in TOOL_NAMES:
        llm.register_function(name, _make_handler(session))
    # Live transfer (operations plan, Task E10). The tool list is built per call from the
    # calendar state, so the handler is registered only on the calls where the model was
    # given the tool: a model that cannot see it cannot call it, and a model that
    # hallucinates the name finds nothing registered.
    if session.transfer_enabled:
        llm.register_function(TRANSFER_TOOL, _make_transfer_handler(session))


IGNORED_TOOL_RETRIES = 1


def _make_handler(session: VoiceSession):
    async def handler(params: FunctionCallParams):
        now = session.clock.now()
        session.tool_called_this_turn = True
        args = dict(params.arguments or {})
        ignored, rejection = tool_refusal(
            session.slots,
            params.function_name,
            args,
            session.cfg,
            session.ref.channel,
            session.ref.caller_phone,
        )
        if ignored and session.ignored_tools < IGNORED_TOOL_RETRIES:
            # The call changed nothing: the step does not offer this tool, the slot holds
            # nothing to change, or the caller asked a question instead of answering. Nothing
            # was written and nothing is said. The spec's answer was to re-ask the open
            # question (slot engine design, §7), but on the founder's call that turned "can
            # you book me that facial?" into a bare "What did you have in mind?" with no
            # answer in front of it, twice. The model gets the turn back instead, with the
            # step's own tools and the whole conversation in its context; the budget above
            # stops it looping.
            session.ignored_tools += 1
            logger.info(
                "tool {} refused; the model answers instead: {}",
                params.function_name,
                rejection or "not offered at this step",
            )
            result = {"spoken": False, "outcome": "none", "ignored": True}
            if rejection:
                # A reason the model can act on, rather than a silent no (2026-09-11 memo,
                # decision 6). It is a function response: never spoken, never stored.
                result["rejection"] = rejection
            await params.result_callback(
                result, properties=FunctionCallResultProperties(run_llm=True)
            )
            return
        slots, spoken, outcome, ended, _speaks = await run_tool(
            session.caps,
            session.ref,
            session.slots,
            params.function_name,
            args,
            now,
        )
        session.slots = slots
        if isinstance(outcome, Completed):
            session.has_completed = True
        if isinstance(outcome, Captured):
            session.band = (
                3 if outcome.item_type.startswith("escalation_") else max(session.band, 2)
            )
        if session.slots.ended_flow:
            session.slots = session.slots.with_(flow=None, ended_flow=False)
        lines = list(spoken)
        if not ended:
            question = next_question(session, now)
            if question:
                lines.append(question)
                # Recorded against the record the tool just moved, so the same question is
                # not repeated word for word on a later side answer at the same step.
                session.remember_question(question)
        sync_context(session, now)
        for text in lines:
            await params.llm.push_frame(TTSSpeakFrame(text=text, append_to_context=True))
        await params.result_callback(
            {
                "spoken": bool(lines),
                "outcome": outcome.kind if outcome else "none",
                "ignored": ignored,
            },
            properties=FunctionCallResultProperties(run_llm=False),
        )
        if ended:
            session.ended = True
            if session.worker is not None:
                await session.worker.queue_frames([EndFrame()])

    return handler


def _make_transfer_handler(session: VoiceSession):
    """`transfer_to_human`: hand the caller to the staffed back-line, or file a callback.

    The order is the honest one. The caller hears `scripts.transferring` first, because it
    promises an attempt and nothing more, and only then is the carrier asked. If the carrier
    refuses or never answers within the budget, the Tier C `transfer` capability files an
    urgent item *before* the human-request wording is spoken, so the sentence the caller
    hears is backed by a row someone has to work.

    On success no EndFrame is queued. `TelnyxFrameSerializer` hangs the call up when it sees
    one (`auto_hang_up` is on by default), which would drop the very leg we just handed over.
    """

    async def handler(params: FunctionCallParams):
        cfg, now = session.cfg, session.clock.now()
        # Band 3 either way: the caller asked for a person, and that is what the nightly
        # audit is looking for whether or not the carrier played along.
        session.band = 3
        await params.llm.push_frame(
            TTSSpeakFrame(
                text=render_script("transferring", cfg, now, urgent=False),
                append_to_context=True,
            )
        )
        ok = await attempt_transfer(
            session.transfer, session.call_control_id, cfg.transfer_number
        )
        if ok:
            session.transferred = True
            session.ended = True
            suppress_auto_hangup(session.hangup_params)
            outcome = Transferred(number_masked=mask_number(cfg.transfer_number or ""))
        else:
            try:
                outcome = await session.caps.transfer(session.ref, TransferRequest())
            except Exception as e:  # noqa: BLE001  ledger down: nothing was filed either
                logger.exception("transfer fallback could not file a callback: {}", e)
                outcome = Refused(reason="unavailable")
            await params.llm.push_frame(
                TTSSpeakFrame(
                    text=render(outcome, cfg, now, channel=session.ref.channel),
                    append_to_context=True,
                )
            )
        await params.result_callback(
            {"spoken": True, "outcome": outcome.kind},
            properties=FunctionCallResultProperties(run_llm=False),
        )

    return handler
