"""initial

Revision ID: 0001
Revises: 
Create Date: 2026-09-02 01:17:07.912035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('record_type', sa.String(length=32), nullable=False),
    sa.Column('record_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='runtime'
    )
    op.create_index('ix_audit_record', 'audit_log', ['record_type', 'record_id'], unique=False, schema='runtime')
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='runtime'
    )
    op.create_index('ix_jobs_state_run', 'jobs', ['state', 'run_at'], unique=False, schema='runtime')
    op.create_table('tenants',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('last_digest_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='runtime'
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('external_ref', sa.String(length=200), nullable=True),
    sa.Column('caller', sa.String(length=200), nullable=True),
    sa.Column('controller', sa.String(length=10), nullable=False),
    sa.Column('health_context', sa.Boolean(), nullable=False),
    sa.Column('band', sa.Integer(), nullable=True),
    sa.Column('latency_ms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['runtime.tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='runtime'
    )
    op.create_index('ix_conv_lookup', 'conversations', ['tenant_id', 'channel', 'external_ref'], unique=False, schema='runtime')
    op.create_index('ix_conv_tenant_started', 'conversations', ['tenant_id', 'started_at'], unique=False, schema='runtime')
    op.create_table('tenant_config_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['runtime.tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'version'),
    schema='runtime'
    )
    op.create_table('tenant_numbers',
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['runtime.tenants.id'], ),
    sa.PrimaryKeyConstraint('number'),
    schema='runtime'
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('urgency', sa.String(length=10), nullable=False),
    sa.Column('service_id', sa.String(length=64), nullable=True),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('preferred_window', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('health_context', sa.Boolean(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('owner', sa.String(length=200), nullable=False),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=200), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['runtime.conversations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['runtime.tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='runtime'
    )
    op.create_index('ix_items_breach', 'items', ['due_at'], unique=False, schema='runtime', postgresql_where=sa.text("state = 'open' AND escalated_at IS NULL"))
    op.create_index('ix_items_tenant_state_due', 'items', ['tenant_id', 'state', 'due_at'], unique=False, schema='runtime')
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['runtime.conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='runtime'
    )
    op.create_index('ix_msg_conv', 'messages', ['conversation_id', 'id'], unique=False, schema='runtime')
    op.create_table('usage_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('qty', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['runtime.conversations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['runtime.tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='runtime'
    )
    op.create_index('ix_usage_conv', 'usage_events', ['conversation_id'], unique=False, schema='runtime')
    op.create_index('ix_usage_tenant_created', 'usage_events', ['tenant_id', 'created_at'], unique=False, schema='runtime')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usage_tenant_created', table_name='usage_events', schema='runtime')
    op.drop_index('ix_usage_conv', table_name='usage_events', schema='runtime')
    op.drop_table('usage_events', schema='runtime')
    op.drop_index('ix_msg_conv', table_name='messages', schema='runtime')
    op.drop_table('messages', schema='runtime')
    op.drop_index('ix_items_tenant_state_due', table_name='items', schema='runtime')
    op.drop_index('ix_items_breach', table_name='items', schema='runtime', postgresql_where=sa.text("state = 'open' AND escalated_at IS NULL"))
    op.drop_table('items', schema='runtime')
    op.drop_table('tenant_numbers', schema='runtime')
    op.drop_table('tenant_config_versions', schema='runtime')
    op.drop_index('ix_conv_tenant_started', table_name='conversations', schema='runtime')
    op.drop_index('ix_conv_lookup', table_name='conversations', schema='runtime')
    op.drop_table('conversations', schema='runtime')
    op.drop_table('tenants', schema='runtime')
    op.drop_index('ix_jobs_state_run', table_name='jobs', schema='runtime')
    op.drop_table('jobs', schema='runtime')
    op.drop_index('ix_audit_record', table_name='audit_log', schema='runtime')
    op.drop_table('audit_log', schema='runtime')
    # ### end Alembic commands ###
