"""text channels

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-02 03:20:40.474731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbound_messages',
    sa.Column('provider_message_id', sa.String(length=200), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('provider_message_id'),
    schema='runtime'
    )
    op.create_table('sms_optouts',
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'phone'),
    schema='runtime'
    )
    op.create_table('textbacks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='runtime'
    )
    op.create_index('ix_textback_lookup', 'textbacks', ['tenant_id', 'phone', 'sent_at'], unique=False, schema='runtime')
    op.add_column('conversations', sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True), schema='runtime')
    op.add_column('conversations', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True), schema='runtime')
    op.add_column('conversations', sa.Column('followup_sent_at', sa.DateTime(timezone=True), nullable=True), schema='runtime')
    op.add_column('conversations', sa.Column('external_session', sa.String(length=200), nullable=True), schema='runtime')
    op.drop_index(op.f('ix_conv_lookup'), table_name='conversations', schema='runtime')
    op.create_index('ix_conv_lookup', 'conversations', ['tenant_id', 'channel', 'external_ref', 'last_message_at'], unique=False, schema='runtime')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conv_lookup', table_name='conversations', schema='runtime')
    op.create_index(op.f('ix_conv_lookup'), 'conversations', ['tenant_id', 'channel', 'external_ref'], unique=False, schema='runtime')
    op.drop_column('conversations', 'external_session', schema='runtime')
    op.drop_column('conversations', 'followup_sent_at', schema='runtime')
    op.drop_column('conversations', 'closed_at', schema='runtime')
    op.drop_column('conversations', 'last_message_at', schema='runtime')
    op.drop_index('ix_textback_lookup', table_name='textbacks', schema='runtime')
    op.drop_table('textbacks', schema='runtime')
    op.drop_table('sms_optouts', schema='runtime')
    op.drop_table('inbound_messages', schema='runtime')
    # ### end Alembic commands ###
