"""slack threads

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-02 04:09:51.111983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('slack_channel', sa.String(length=32), nullable=True), schema='runtime')
    op.add_column('conversations', sa.Column('slack_ts', sa.String(length=32), nullable=True), schema='runtime')
    op.create_index('ix_conv_slack_ts', 'conversations', ['slack_ts'], unique=False, schema='runtime')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conv_slack_ts', table_name='conversations', schema='runtime')
    op.drop_column('conversations', 'slack_ts', schema='runtime')
    op.drop_column('conversations', 'slack_channel', schema='runtime')
    # ### end Alembic commands ###
