import { type DailyStats } from "wasp/entities";
import { HttpError, prisma } from "wasp/server";
import { type GetDailyStats } from "wasp/server/operations";

type DailyStatsValues = {
  dailyStats: DailyStats;
  weeklyStats: DailyStats[];
};

export const getDailyStats: GetDailyStats<
  void,
  DailyStatsValues | null
> = async (_args, context) => {
  if (!context.user) {
    throw new HttpError(
      401,
      "Only authenticated users are allowed to perform this operation",
    );
  }

  if (!context.user.isAdmin) {
    throw new HttpError(
      403,
      "Only admins are allowed to perform this operation",
    );
  }

  const statsQuery = {
    orderBy: {
      date: "desc",
    },
  } as const;

  const [dailyStats, weeklyStats] = await prisma.$transaction([
    context.entities.DailyStats.findFirst(statsQuery),
    context.entities.DailyStats.findMany({ ...statsQuery, take: 7 }),
  ]);

  if (!dailyStats) {
    // `null`, not `undefined`: react-query v5 treats an undefined query result as
    // an error ("Query data cannot be undefined") and logged one on every focus of
    // the admin analytics page until the first stats row existed (founder report
    // 2026-09-03). The page renders its "No daily stats generated yet" overlay on
    // a null result.
    console.log(
      "\x1b[34mNote: No daily stats have been generated by the calculateDailyStatsJob yet. \x1b[0m",
    );
    return null;
  }

  return { dailyStats, weeklyStats };
};
