"""The only place outcome wording is produced.

Structural honesty layer 2 (spec §5): the sentence that describes what happened is rendered
from the tenant's `scripts`, never generated by a model. A `Refused` outcome can therefore not
claim anything was sent or filed, whatever the model believed it had done.
"""

from __future__ import annotations

from datetime import datetime

from spatalk.brain.audio_tags import strip_audio_tags
from spatalk.brain.hours import BusinessCalendar, humanize_due
from spatalk.brain.outcomes import Captured, Completed, LinkSent, Outcome, Refused, Transferred
from spatalk.tenants.schema import TenantConfig

COMPLETED_TEMPLATE = "Done. Your {service} is {verb} for {when}. Your reference is {ref}."

# Channels where a booking link is shown inline instead of being texted separately.
TEXT_CHANNELS = ("chat", "instagram", "messenger")

# escalation_<reason> item types to the fixed script that answers them.
_ESCALATION_SCRIPTS = {
    "emergency": "emergency",
    "clinical": "clinical",
    "complaint": "complaint",
    "payment": "payment",
    "legal": "complaint",
}


def _values(cfg: TenantConfig, now: datetime, urgent: bool, **extra) -> dict[str, str]:
    cal = BusinessCalendar(cfg)
    due = cal.due_for("urgent" if urgent else "normal", now)
    values = {
        "confirm_by": humanize_due(due, now, cfg.timezone, urgent),
        "service": "",
        "url": "",
        "name": cfg.name,
        "phone": cfg.public_phone or "the clinic's usual number",
        "booking_url": cfg.booking_url_default,
        "sms_number": cfg.sms_from_number or cfg.public_phone or "the clinic",
    }
    values.update(extra)
    return values


def _fill(template: str, cfg: TenantConfig, now: datetime, urgent: bool, **extra) -> str:
    return template.format(**_values(cfg, now, urgent, **extra))


def render_script(
    name: str, cfg: TenantConfig, now: datetime, urgent: bool = True, **extra
) -> str:
    """Render one fixed script by its `Scripts` field name (`disclosure`, `clinical`, ...)."""
    template = getattr(cfg.scripts, name)
    return _fill(template, cfg, now, urgent, **extra)


def render(outcome: Outcome, cfg: TenantConfig, now: datetime, channel: str = "voice") -> str:
    """Turn a closed outcome into the sentence the caller hears or reads."""
    text = _render(outcome, cfg, now, channel)
    return text if channel == "voice" else strip_audio_tags(text)


def _render(outcome: Outcome, cfg: TenantConfig, now: datetime, channel: str) -> str:
    s = cfg.scripts
    if isinstance(outcome, Captured):
        urgent = outcome.urgency == "urgent"
        confirm = humanize_due(outcome.confirm_by, now, cfg.timezone, urgent)
        if outcome.item_type == "send_link":
            return s.link_captured.format(confirm_by=confirm, service="the treatment")
        if outcome.item_type.startswith("escalation_"):
            reason = outcome.item_type.removeprefix("escalation_")
            if reason in ("clinical", "emergency") and channel != "voice":
                # "Hang up" and "at this number" make no sense in a chat window.
                return getattr(s, f"{reason}_text").format(confirm_by=confirm)
            template = getattr(s, _ESCALATION_SCRIPTS.get(reason, "human_request"))
            return template.format(confirm_by=confirm)
        return s.captured.format(confirm_by=confirm)
    if isinstance(outcome, LinkSent):
        service = cfg.service(outcome.service_id)
        name = service.name if service else "that treatment"
        if channel in TEXT_CHANNELS:
            return _fill(s.link_shown, cfg, now, urgent=False, service=name, url=outcome.url)
        return _fill(s.link_sent, cfg, now, urgent=False, service=name)
    if isinstance(outcome, Refused):
        if outcome.reason == "payment":
            return _fill(s.payment, cfg, now, urgent=True)
        return _fill(getattr(s, f"refuse_{outcome.reason}"), cfg, now, urgent=False)
    if isinstance(outcome, Transferred):
        # The same sentence the voice handler speaks before it dials, rendered from the same
        # script so the two can never drift (operations plan, Task E10). It promises a
        # connection attempt, not a completed action, which is what actually happened.
        return _fill(s.transferring, cfg, now, urgent=False)
    if isinstance(outcome, Completed):
        return COMPLETED_TEMPLATE.format(
            service="appointment",
            verb=outcome.verb,
            when=outcome.when,
            ref=outcome.platform_ref,
        )
    raise TypeError(f"unknown outcome {outcome!r}")
