import asyncio
from logging.config import fileConfig

from alembic import context
from sqlalchemy import pool, text
from sqlalchemy.ext.asyncio import async_engine_from_config

import spatalk.models  # noqa: F401  (registers tables)
import spatalk.social.models  # noqa: F401  (instagram plan, Task D1: the social tables)
from spatalk.db import Base
from spatalk.settings import get_settings

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)
config.set_main_option("sqlalchemy.url", get_settings().database_url)
target_metadata = Base.metadata


def include_object(obj, name, type_, reflected, compare_to) -> bool:
    """Autogenerate compares the `runtime` schema and nothing else.

    `include_schemas=True` makes alembic reflect every schema in the database, and the
    portal owns `public` in the same database (CLAUDE.md non-negotiable 7: two planes, zero
    shared tables). Without this filter an autogenerated revision drops the portal's tables.
    """
    schema = getattr(obj, "schema", None) or getattr(getattr(obj, "table", None), "schema", None)
    return schema == "runtime"


def run_migrations_offline() -> None:
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        include_schemas=True,
        include_object=include_object,
        version_table_schema="runtime",
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection) -> None:
    connection.execute(text("CREATE SCHEMA IF NOT EXISTS runtime"))
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        include_schemas=True,
        include_object=include_object,
        version_table_schema="runtime",
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
        # `CREATE SCHEMA` above opens the connection's transaction, so alembic leaves
        # the commit to us (MigrationContext.begin_transaction is a no-op when the
        # connection is already in a transaction).
        await connection.commit()
    await connectable.dispose()


def run_migrations_online() -> None:
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
