/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/internal/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tenants */
        get: operations["list_tenants_internal_tenants_get"];
        put?: never;
        /** Create Tenant */
        post: operations["create_tenant_internal_tenants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/tenants/from-bundle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Tenant From Bundle
         * @description The five-file YAML bundle, uploaded instead of read from disk.
         *
         *     The onboarding wizard (Task C5) posts the files the founder was given; they go through
         *     exactly the rules `spatalk tenant import` uses, so a bundle that imports from the CLI
         *     imports from the portal and the other way round.
         */
        post: operations["create_tenant_from_bundle_internal_tenants_from_bundle_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/tenants/from-basics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Tenant From Basics
         * @description A tenant from the basics alone: the starter bundle rendered around them.
         *
         *     The wizard's "start from the basics" path (onboarding roadmap, section 4). The five
         *     texts go through `config_from_texts` like an upload would, so the tenant is judged by
         *     the same rules. Unlike `from-bundle`, which deliberately versions an existing tenant,
         *     this refuses one that already exists: a form must never overwrite a configured clinic.
         */
        post: operations["create_tenant_from_basics_internal_tenants_from_basics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/tenants/{tenant_id}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_internal_tenants__tenant_id__config_get"];
        /** Put Config */
        put: operations["put_config_internal_tenants__tenant_id__config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/tenants/{tenant_id}/config/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Config Versions */
        get: operations["list_config_versions_internal_tenants__tenant_id__config_versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/tenants/{tenant_id}/config/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rollback Config
         * @description A rollback is a new version equal to the old one. Nothing is ever deleted.
         */
        post: operations["rollback_config_internal_tenants__tenant_id__config_rollback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/schema/tenant-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tenant Config Schema
         * @description The pydantic models are the single source of truth; the portal's forms are built
         *     from this schema, so a field added anywhere else is a defect.
         */
        get: operations["tenant_config_schema_internal_schema_tenant_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/tenants/{tenant_id}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tenant Usage */
        get: operations["tenant_usage_internal_tenants__tenant_id__usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/tenants/{tenant_id}/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tenant Conversations */
        get: operations["tenant_conversations_internal_tenants__tenant_id__conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Conversation
         * @description Reading a transcript is an audited act, whoever the reader is.
         */
        get: operations["read_conversation_internal_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/tenants/{tenant_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tenant Items */
        get: operations["tenant_items_internal_tenants__tenant_id__items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/items/{item_id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acknowledge Item */
        post: operations["acknowledge_item_internal_items__item_id__acknowledge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/items/{item_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Item */
        post: operations["resolve_item_internal_items__item_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/tenants/{tenant_id}/latency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tenant Latency */
        get: operations["tenant_latency_internal_tenants__tenant_id__latency_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/tenants/{tenant_id}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tenant Health */
        get: operations["tenant_health_internal_tenants__tenant_id__health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/tenants/{tenant_id}/sms-blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sms Blocks */
        get: operations["sms_blocks_internal_tenants__tenant_id__sms_blocks_get"];
        put?: never;
        /** Add Sms Block */
        post: operations["add_sms_block_internal_tenants__tenant_id__sms_blocks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/tenants/{tenant_id}/sms-blocks/{phone}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Sms Block */
        delete: operations["remove_sms_block_internal_tenants__tenant_id__sms_blocks__phone__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/tenants/{tenant_id}/audit/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tenant Latest Audit
         * @description What the admin health page reads (portal plan C5): last night's audit for a tenant.
         */
        get: operations["tenant_latest_audit_internal_tenants__tenant_id__audit_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Runtime Health
         * @description Queue depth for the agency's health page (Task C5), not a liveness probe.
         */
        get: operations["runtime_health_internal_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rates
         * @description The prices behind every `est_cost_cad`, so the portal can show its working.
         */
        get: operations["rates_internal_rates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Audit
         * @description The portal records an act of its own (an export, a settings view it performed).
         */
        post: operations["post_audit_internal_audit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/tenants/{tenant_id}/integrations/messenger/select": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Select Messenger Page
         * @description Finish a Page connection when the person administers more than one Page.
         *
         *     `GET /messenger/callback` cannot choose for them and cannot repeat the exchange (the
         *     OAuth code is single use), so it parks the Pages behind an opaque handle and sends the
         *     browser back to the portal with their names. This is where the choice lands.
         */
        post: operations["select_messenger_page_internal_tenants__tenant_id__integrations_messenger_select_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/tenants/{tenant_id}/integrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tenant Integrations
         * @description One row per provider, connected or not, so the page can draw both cards.
         */
        get: operations["tenant_integrations_internal_tenants__tenant_id__integrations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/tenants/{tenant_id}/integrations/{provider}/connect-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Integration Connect Url
         * @description The Meta authorisation URL, with a signed state carrying the tenant and `return_to`.
         *
         *     The state is what makes this safe to hand out: `/instagram/callback` will only store an
         *     account against the tenant this key-holder named, and will only bounce the browser back
         *     to the address signed here. It is minted per click, because it is good for fifteen
         *     minutes and a settings page can sit open for longer than that.
         */
        get: operations["integration_connect_url_internal_tenants__tenant_id__integrations__provider__connect_url_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/tenants/{tenant_id}/integrations/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Disconnect Integration
         * @description Disconnect: Meta stops sending, then the row and its token go.
         *
         *     The order matters. Unsubscribing needs the token, so it happens first; it is best
         *     effort, and a Meta that refuses does not trap a tenant in a connection they have asked
         *     to end. The answer says which of the two happened.
         */
        delete: operations["disconnect_integration_internal_tenants__tenant_id__integrations__provider__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActorIn */
        ActorIn: {
            /** Actor */
            actor: string;
        };
        /** AuditIn */
        AuditIn: {
            /** Actor */
            actor: string;
            /** Action */
            action: string;
            /** Record Type */
            record_type: string;
            /** Record Id */
            record_id: string;
        };
        /**
         * AuditLatest
         * @description The most recent nightly escalation audit for one tenant.
         *
         *     All three fields are null until the first night has run, so the admin health page can
         *     render "no audit yet" without treating an empty history as an error.
         */
        AuditLatest: {
            /** Day */
            day: string | null;
            /** Created At */
            created_at: string | null;
            /** Report */
            report: {
                [key: string]: unknown;
            } | null;
        };
        /** Body_create_tenant_from_bundle_internal_tenants_from_bundle_post */
        Body_create_tenant_from_bundle_internal_tenants_from_bundle_post: {
            /**
             * Tenant
             * @description tenant.yaml
             */
            tenant: string;
            /**
             * Services
             * @description services.yaml
             */
            services: string;
            /**
             * Knowledge
             * @description knowledge.md
             */
            knowledge: string;
            /**
             * Scripts
             * @description scripts.yaml
             */
            scripts: string;
            /**
             * Guard
             * @description guard.yaml
             */
            guard: string;
            /**
             * Created By
             * @default portal
             */
            created_by: string;
        };
        /** ConfigIn */
        ConfigIn: {
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /**
             * Created By
             * @default portal
             */
            created_by: string;
        };
        /** ConfigOut */
        ConfigOut: {
            /** Version */
            version: number;
            /** Config */
            config: {
                [key: string]: unknown;
            };
        };
        /** ConfigVersionOut */
        ConfigVersionOut: {
            /** Version */
            version: number;
            /** Created By */
            created_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ConnectUrlOut
         * @description Where to send the browser to connect, and how long that link is good for.
         */
        ConnectUrlOut: {
            /** Url */
            url: string;
            /** Expires In */
            expires_in: number;
        };
        /** ConversationDetail */
        ConversationDetail: {
            conversation: components["schemas"]["ConversationFull"];
            /** Messages */
            messages: components["schemas"]["MessageOut"][];
            /** Items */
            items: components["schemas"]["ItemOut"][];
        };
        /** ConversationFull */
        ConversationFull: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Channel */
            channel: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at: string | null;
            /** Duration S */
            duration_s: number | null;
            /** Band */
            band: number | null;
            /** Health Context */
            health_context: boolean;
            /** Controller */
            controller: string;
            /** Item Count */
            item_count: number;
            /** Caller Masked */
            caller_masked: string | null;
            /** Tenant Id */
            tenant_id: string;
            /** Caller */
            caller: string | null;
            /** External Ref */
            external_ref: string | null;
            /** Notes */
            notes: string | null;
            /** Notes At */
            notes_at: string | null;
        };
        /** ConversationPage */
        ConversationPage: {
            /** Items */
            items: components["schemas"]["ConversationRow"][];
            /** Total */
            total: number;
        };
        /** ConversationRow */
        ConversationRow: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Channel */
            channel: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at: string | null;
            /** Duration S */
            duration_s: number | null;
            /** Band */
            band: number | null;
            /** Health Context */
            health_context: boolean;
            /** Controller */
            controller: string;
            /** Item Count */
            item_count: number;
            /** Caller Masked */
            caller_masked: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IntegrationOut
         * @description What the portal may know about a connected Meta account.
         *
         *     Never the token: not the plaintext, not the ciphertext, not its length. The portal has
         *     no use for it and no way to keep it as safely as the runtime does.
         */
        IntegrationOut: {
            /** Provider */
            provider: string;
            /** Connected */
            connected: boolean;
            /** Configured */
            configured: boolean;
            /** External Id */
            external_id?: string | null;
            /** Display Name */
            display_name?: string | null;
            /** Token Expires At */
            token_expires_at?: string | null;
            /**
             * Scopes
             * @default []
             */
            scopes: string[];
            /**
             * Needs Reconnect
             * @default false
             */
            needs_reconnect: boolean;
            /** Connected By */
            connected_by?: string | null;
            /** Connected At */
            connected_at?: string | null;
        };
        /**
         * IntegrationRemoved
         * @description `disconnected` is the row; `unsubscribed` is whether Meta agreed to stop sending.
         */
        IntegrationRemoved: {
            /** Provider */
            provider: string;
            /** Disconnected */
            disconnected: boolean;
            /** Unsubscribed */
            unsubscribed: boolean;
        };
        /**
         * ItemOut
         * @description Every column of `runtime.items`. There is no free-text column and never will be.
         */
        ItemOut: {
            /** Id */
            id: number;
            /** Tenant Id */
            tenant_id: string;
            /** Conversation Id */
            conversation_id: string | null;
            /** Type */
            type: string;
            /** Urgency */
            urgency: string;
            /** Service Id */
            service_id: string | null;
            /** Contact Name */
            contact_name: string | null;
            /** Contact Phone */
            contact_phone: string | null;
            /** Contact Email */
            contact_email: string | null;
            /** Preferred Window */
            preferred_window: {
                [key: string]: unknown;
            };
            /** Channel */
            channel: string;
            /** Health Context */
            health_context: boolean;
            /** Returning Client */
            returning_client: boolean | null;
            /** Practitioner */
            practitioner: string | null;
            /** Concern */
            concern: string | null;
            /** State */
            state: string;
            /**
             * Due At
             * Format: date-time
             */
            due_at: string;
            /** Owner */
            owner: string;
            /** Escalated At */
            escalated_at: string | null;
            /** Acknowledged At */
            acknowledged_at: string | null;
            /** Acknowledged By */
            acknowledged_by: string | null;
            /** Resolved At */
            resolved_at: string | null;
            /** Resolved By */
            resolved_by: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Summary */
            summary: string;
            /** Service Name */
            service_name: string | null;
            /** Preferred Text */
            preferred_text: string;
            /** Notes */
            notes: string | null;
        };
        /** LatencyDay */
        LatencyDay: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Turns */
            turns: number;
            /** P50 Ms */
            p50_ms: number;
            /** P95 Ms */
            p95_ms: number;
        };
        /** MessageOut */
        MessageOut: {
            /** Role */
            role: string;
            /** Text */
            text: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * MessengerPageSelectIn
         * @description Which Facebook Page the owner picked, and the handle the callback handed them.
         */
        MessengerPageSelectIn: {
            /** Pending */
            pending: string;
            /** Page Id */
            page_id: string;
        };
        /**
         * MessengerPageSelected
         * @description The connected Page. No token, encrypted or otherwise, ever crosses this boundary.
         */
        MessengerPageSelected: {
            /** Tenant Id */
            tenant_id: string;
            /** Provider */
            provider: string;
            /** External Id */
            external_id: string;
            /** Display Name */
            display_name: string;
        };
        /** NumberOut */
        NumberOut: {
            /** Number */
            number: string;
            /** Kind */
            kind: string;
        };
        /** RollbackIn */
        RollbackIn: {
            /** Version */
            version: number;
            /**
             * Created By
             * @default portal
             */
            created_by: string;
        };
        /** RuntimeHealth */
        RuntimeHealth: {
            /** Ok */
            ok: boolean;
            /** Queued Jobs */
            queued_jobs: number;
            /** Oldest Queued Age S */
            oldest_queued_age_s: number | null;
            /** Dead Jobs */
            dead_jobs: number;
        };
        /** SmsBlockIn */
        SmsBlockIn: {
            /** Phone */
            phone: string;
            /** Actor */
            actor: string;
        };
        /** SmsBlockOut */
        SmsBlockOut: {
            /** Phone */
            phone: string;
            /** Until */
            until: string | null;
            /** Reason */
            reason: string;
            /** Created By */
            created_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SmsBlockRemoved */
        SmsBlockRemoved: {
            /** Removed */
            removed: boolean;
        };
        /** TenantBasicsIn */
        TenantBasicsIn: {
            /**
             * Id
             * @description tenant id: lowercase letters, digits, hyphens
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Timezone
             * @description IANA zone, e.g. America/Toronto
             */
            timezone: string;
            /**
             * Hours
             * @description mon..sun to [start, end] HH:MM spans; a missing or empty day is closed
             */
            hours: {
                [key: string]: [
                    string,
                    string
                ][];
            };
            /**
             * Booking Url
             * Format: uri
             */
            booking_url: string;
            /**
             * Public Phone
             * @description the clinic's own number, E.164, or empty
             * @default
             */
            public_phone: string;
            /**
             * Owner Name
             * @default
             */
            owner_name: string;
            /** Owner Email */
            owner_email: string;
            /**
             * Assistant Name
             * @default Ava
             */
            assistant_name: string;
            /**
             * Created By
             * @default portal
             */
            created_by: string;
        };
        /** TenantCreated */
        TenantCreated: {
            /** Id */
            id: string;
            /** Version */
            version: number;
        };
        /** TenantHealth */
        TenantHealth: {
            /** Open Items */
            open_items: number;
            /** Overdue Items */
            overdue_items: number;
            /** Last Call At */
            last_call_at: string | null;
            /** Last Sms At */
            last_sms_at: string | null;
            /** Config Version */
            config_version: number | null;
            /**
             * Sms Muted Numbers
             * @default 0
             */
            sms_muted_numbers: number;
            /**
             * Sms Blocked Numbers
             * @default 0
             */
            sms_blocked_numbers: number;
            /**
             * Sms Replies Today
             * @default 0
             */
            sms_replies_today: number;
        };
        /** TenantSummary */
        TenantSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Version */
            version: number;
            /** Numbers */
            numbers: components["schemas"]["NumberOut"][];
            /** Sms From Number */
            sms_from_number: string | null;
            /** Integration Tier */
            integration_tier: string;
        };
        /** UsageDay */
        UsageDay: {
            /** Calls */
            calls: number;
            /** Call Minutes */
            call_minutes: number;
            /** Sms In */
            sms_in: number;
            /** Sms Out */
            sms_out: number;
            /** Chats */
            chats: number;
            /** Ig Messages */
            ig_messages: number;
            /** Llm Input Tokens */
            llm_input_tokens: number;
            /** Llm Cached Tokens */
            llm_cached_tokens: number;
            /** Llm Output Tokens */
            llm_output_tokens: number;
            /** Tts Chars */
            tts_chars: number;
            /** Est Cost Cad */
            est_cost_cad: number;
            /**
             * Date
             * Format: date
             */
            date: string;
        };
        /** UsageOut */
        UsageOut: {
            /** Days */
            days: components["schemas"]["UsageDay"][];
            totals: components["schemas"]["UsageTotals"];
        };
        /** UsageTotals */
        UsageTotals: {
            /** Calls */
            calls: number;
            /** Call Minutes */
            call_minutes: number;
            /** Sms In */
            sms_in: number;
            /** Sms Out */
            sms_out: number;
            /** Chats */
            chats: number;
            /** Ig Messages */
            ig_messages: number;
            /** Llm Input Tokens */
            llm_input_tokens: number;
            /** Llm Cached Tokens */
            llm_cached_tokens: number;
            /** Llm Output Tokens */
            llm_output_tokens: number;
            /** Tts Chars */
            tts_chars: number;
            /** Est Cost Cad */
            est_cost_cad: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionOut */
        VersionOut: {
            /** Version */
            version: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_tenants_internal_tenants_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantSummary"][];
                };
            };
        };
    };
    create_tenant_internal_tenants_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Actor"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_tenant_from_bundle_internal_tenants_from_bundle_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Actor"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_tenant_from_bundle_internal_tenants_from_bundle_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_tenant_from_basics_internal_tenants_from_basics_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Actor"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantBasicsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_internal_tenants__tenant_id__config_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_config_internal_tenants__tenant_id__config_put: {
        parameters: {
            query?: never;
            header?: {
                "X-Actor"?: string | null;
            };
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_config_versions_internal_tenants__tenant_id__config_versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigVersionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rollback_config_internal_tenants__tenant_id__config_rollback_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Actor"?: string | null;
            };
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RollbackIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tenant_config_schema_internal_schema_tenant_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    tenant_usage_internal_tenants__tenant_id__usage_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tenant_conversations_internal_tenants__tenant_id__conversations_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                channel?: string | null;
                band?: number | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_conversation_internal_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Actor"?: string | null;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tenant_items_internal_tenants__tenant_id__items_get: {
        parameters: {
            query?: {
                state?: "open" | "acknowledged" | "resolved" | "expired" | "all";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acknowledge_item_internal_items__item_id__acknowledge_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Actor"?: string | null;
            };
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActorIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_item_internal_items__item_id__resolve_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Actor"?: string | null;
            };
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActorIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tenant_latency_internal_tenants__tenant_id__latency_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LatencyDay"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tenant_health_internal_tenants__tenant_id__health_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantHealth"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sms_blocks_internal_tenants__tenant_id__sms_blocks_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmsBlockOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_sms_block_internal_tenants__tenant_id__sms_blocks_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Actor"?: string | null;
            };
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SmsBlockIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmsBlockOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_sms_block_internal_tenants__tenant_id__sms_blocks__phone__delete: {
        parameters: {
            query: {
                actor: string;
            };
            header?: {
                "X-Actor"?: string | null;
            };
            path: {
                tenant_id: string;
                phone: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmsBlockRemoved"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tenant_latest_audit_internal_tenants__tenant_id__audit_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLatest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runtime_health_internal_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeHealth"];
                };
            };
        };
    };
    rates_internal_rates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    post_audit_internal_audit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuditIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    select_messenger_page_internal_tenants__tenant_id__integrations_messenger_select_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessengerPageSelectIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessengerPageSelected"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tenant_integrations_internal_tenants__tenant_id__integrations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    integration_connect_url_internal_tenants__tenant_id__integrations__provider__connect_url_get: {
        parameters: {
            query?: {
                return_to?: string | null;
            };
            header?: {
                "X-Actor"?: string | null;
            };
            path: {
                tenant_id: string;
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectUrlOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disconnect_integration_internal_tenants__tenant_id__integrations__provider__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Actor"?: string | null;
            };
            path: {
                tenant_id: string;
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationRemoved"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
